trigger:
- lithium

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
    addToPath: true
    architecture: 'x64'
  name: pyTools
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- script: $(pyTools.pythonLocation)/bin/pip install https://github.com/BunsenLabs/dockerbuild/releases/download/1.0.1/dockerbuild-1.0.1-py3-none-any.whl
- script: mkdir -p $(Build.SourcesDirectory)/out
  displayName: Create .deb package output directory
- script: $(pyTools.pythonLocation)/bin/dockerbuild build -s $(Build.SourcesDirectory) -a amd64 -o $(Build.SourcesDirectory)/out -t 7200
  displayName: Build .deb package