trigger:
  - lithium

pool:
  vmImage: 'ubuntu-latest'

variables:
  PythonVersion: '3.8'
  DockerBuildVersion: '1.0.1'
  DockerVersion: '17.09.0-ce'

steps:
  - task: UsePythonVersion@0
    displayName: Install Python runtime
    name: pyTools
    inputs:
      versionSpec: $(PythonVersion)
      addToPath: true
      architecture: 'x64'

  - task: DockerInstaller@0
    displayName: Install and start Docker daemon
    inputs:
      dockerVersion: $(DockerVersion)

  - script: $(pyTools.pythonLocation)/bin/pip install https://github.com/BunsenLabs/dockerbuild/releases/download/$(DockerBuildVersion)/dockerbuild-$(DockerBuildVersion)-py3-none-any.whl
    displayName: Install dockerbuild wheel

  - script: mkdir -p $(Build.SourcesDirectory)/out
    displayName: Create .deb package output directory

  - script: $(pyTools.pythonLocation)/bin/dockerbuild build -s $(Build.SourcesDirectory) -a amd64 -o $(Build.SourcesDirectory)/out -t 7200
    displayName: Build .deb package
